spring:
  datasource:
    url: jdbc:h2:mem:testdb?useSSL=false&serverTimezone=UTC
    driver-class-name: org.h2.Driver
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:password}
  h2:
    console:
      enabled: true
      path: /h2-console
